### ISSUE TITLE
What about the new ROM?

### ISSUE THREAD

**Issue by ajmz** [Smosia/hennessy_3.10.72#1]
I am a member of the telegram group,may I ask you what about the new ROM?Thanks a lot.

**Comment by JosefKuchar** [comment]
RIP :/

**Comment by ajmz** [comment]
Any plan to release lineageos 14.1 for Hennessy?
I only use Wi-Fi, phone function is nothing to do with me.
Thanks.

**Comment by JosefKuchar** [comment]
It's not worth for any1 to invest time into this fucking MTK shit.
